const env = require("dotenv").config()
if(!process.env.port) return console.log("Missing value for `port` in .env!")
if(!process.env.password) return console.log("Missing value for `password` in .env!")
if(!process.env.token) return console.log("Missing value for `token` in .env!")
const { AutoTasker } = require("./Loaders/Autotasks.js")
const { commander } = require("./Loaders/Commands.js")
const { structurer } = require("./Loaders/Structures")
const { eventer } = require("./Loaders/events")
const { bot } = require("./bot.js")
AutoTasker()
commander()
structurer()
eventer()
console.log(`Currently hanging out on ${process.pid}!`)
bot.login(process.env.token)
process.traceDeprecation = true
